server:
  port: 8082
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_order?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env:
  1234567
girl:
  name: akali
  age: 23
