server:
  port: 8081
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_product?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env:
  dev-test2
