server:
  port: 9001
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/User?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
